Спринт3. Практические задания. Часть 1
AlexVolkow/architecture-sprint-3 pull request #1
Opened 2024-12-07 15:51 UTC by AlexVolkow

2024-12-11 20:51 UTC, dchekushin requested changes

2024-12-11 20:51 UTC, dchekushin commented on Project_template_part_1.md
> +- **поддомен** просмотр телеметрии
Добавь еще домены: "Пользователи", "Сценарии и автоматизация" и "Управление домом".

2024-12-11 20:51 UTC, dchekushin commented on part1/Context.puml
> +Rel(admin,WarmHouseSystem, "Управляет системой")
Укажи протоколы и технологии взаимодействия, например http, между модулями системы.

2024-12-11 20:51 UTC, dchekushin commented on part1/Context.puml
> +Person(admin, "Administrator", "Администратор системы")
Выдели мобильное приложение или веб-сайт отдельным контейнером, пользователь взаимодействует с ними,  а не с "Система Теплый дом" на прямую.

2024-12-11 20:51 UTC, dchekushin commented on part1/Context.puml
> +System(WarmHouseSystem, "Система Теплный дом", "Система управления датчиками и параметрами отопления")
Укажи технологии используемые в монолите (Java, PostgreSQL и тд.)

2024-12-11 20:51 UTC, dchekushin commented on part1/Container.puml
> +
Рекомендую добавить сервисы согласно выделенным в первой части доменам предметной области:
- Аутентификации и управление пользователями
- Сценарии автоматизации
- Управление домами

2024-12-11 20:51 UTC, dchekushin commented on part1/ER.puml
> +    *device_state: text
Статус устройств стоит хранить в виде enum (Включено / выключено). По мере развития системы, могут добавится устройства с дополнительными рабочими режимами и соответственно статусами.

2024-12-11 20:51 UTC, dchekushin commented on part1/ER.puml
> +    email: text
Здесь можем предусмотреть пароль пользователя. Как писал выше, в системе нужен механизм аутентификации  пользователя.

2024-12-11 20:51 UTC, dchekushin commented on part1/ER.puml
> +
Подумай, как на уровне данных будем реализовывать требование:
"Покупатели могут программировать систему для управления различными модулями в соответствии со своими потребностями."

2024-12-12 17:29 UTC, AlexVolkow commented on Project_template_part_1.md
> +- **поддомен** просмотр телеметрии
Добавил

2024-12-12 17:29 UTC, AlexVolkow commented on part1/Context.puml
> +Rel(admin,WarmHouseSystem, "Управляет системой")
Добавил

2024-12-12 17:29 UTC, AlexVolkow commented on part1/Context.puml
> +Person(admin, "Administrator", "Администратор системы")
Добавил

2024-12-12 17:29 UTC, AlexVolkow commented on part1/Context.puml
> +System(WarmHouseSystem, "Система Теплный дом", "Система управления датчиками и параметрами отопления")
Добавил

2024-12-12 17:29 UTC, AlexVolkow commented on part1/Container.puml
> +
Добавил

2024-12-12 17:30 UTC, AlexVolkow commented on part1/ER.puml
> +    *device_state: text
Добавил

2024-12-12 17:30 UTC, AlexVolkow commented on part1/ER.puml
> +    email: text
Добавил хеш пароля и соль пользователя

2024-12-12 17:30 UTC, AlexVolkow commented on part1/ER.puml
> +
Добавил сущности Сценарий, Шаг сценария, Триггер и Действие

2024-12-13 08:38 UTC, dchekushin approved these changes

2025-02-23 09:12 UTC, merged